services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: qa-local-backend-local
    container_name: qa-local-backend
    ports:
      - "22083:9044"
      - "22085:9104"

  frontend:
    image: machackgo/qa-local-frontend:latest
    container_name: qa-local-frontend
    environment:
      BACKEND_URL: http://backend:9044
    ports:
      - "22081:7044"
    depends_on:
      - backend
