services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: qa-api-backend
    container_name: qa-api-backend
    ports:
      - "22014:9004"
      - "22114:9101"
    env_file:
      - /home/group04/qa.env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: qa-api-frontend
    container_name: qa-api-frontend
    environment:
      BACKEND_URL: http://backend:9004
    ports:
      - "22004:7004"
    depends_on:
      - backend
